### ISSUE TITLE
Unknown error message with large input

### ISSUE THREAD

**Issue by joshua-shuhan** [SamuelHuang2019/dsaa-project-matrix#4]
The code gives the correct output matrix without any error message when the input matrix is small (eg. 10, 10).
The code gives the correct output but error message "Invalid Matrix Size" when the input matrix is larger (eg. 200, 50).
Need further testing.

I commit a new test code.

**Comment by SamuelHuang2019** [comment]
More details of this issue:

```python
m1 = Matrix(range(10000), 100, 100)
```
While running this line, module will throw error message

```shell
Invalid matrix size
```

It is already verified that for small matrices, the generation and multiplication are all functioning normally.

For example

```python
m1 = Matrix(range(16), 4, 4)
```

**Comment by SamuelHuang2019** [comment]
![image](https://user-images.githubusercontent.com/58419736/100700163-c91c6a80-33d7-11eb-9f31-cb4b3811ec15.png)

Really confused...
Why `10000` is not `10000`? What is the difference?

**Comment by SamuelHuang2019** [comment]
Problem solved!
In Python, `is` and `is not` compares the memory address, for this case, comparing `int` values, we should use `==` and `!=`...

```python
if len(elements) != row * col:
    print('Invalid matrix size')
```
